apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-green
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/203403084713/clusters/cbioportal-prod/apps/ingress-green
      targetRevision: HEAD
      directory:
        recurse: true
      ref: ingress-green
    - repoURL: git@github.com:knowledgesystems/portal-configuration.git
      path: argocd/aws/203403084713/clusters/cbioportal-prod/helm
      targetRevision: HEAD
      directory:
        recurse: true
      ref: portal-configuration
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.12.0
      chart: ingress-nginx
      helm:
        releaseName: ingress-green
        valueFiles:
          - $ingress-green/argocd/aws/203403084713/clusters/cbioportal-prod/apps/ingress-green/values.yaml
          - $portal-configuration/argocd/aws/203403084713/clusters/cbioportal-prod/helm/cbioportal-redis-values.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
