master:
  count: 0
  disableCommands: []
  extraFlags:
    - --maxmemory 8gb
    - --maxmemory-policy volatile-ttl
  nodeSelector:
    workload: redis
  persistence:
    enabled: false
  tolerations:
    - effect: NoSchedule
      key: workload
      operator: Equal
      value: redis
replica:
  replicaCount: 0
  disableCommands: []
  extraFlags:
    - --maxmemory 8gb
    - --maxmemory-policy volatile-ttl
  nodeSelector:
    workload: redis
  persistence:
    enabled: false
  tolerations:
    - effect: NoSchedule
      key: workload
      operator: Equal
      value: redis