---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: cellxgene
  name: cellxgene-deploy-s3-access-example
  labels:
    app: cellxgene
    dataset: pbmc3k-test.h5ad
spec:
  replicas: 1
  selector:
    matchLabels:
      dataset: pbmc3k-test.h5ad
  template:
    metadata:
      labels:
        dataset: pbmc3k-test.h5ad
    spec:
      # serviceAccountName: cellxgene-service-account
      containers:
        - name: cellxgene-app
          image: 'edit01/cellxgene:1.2.0'
          command: ["cellxgene"]
          args: [
            "launch", 
            "-p", 
            "8080", 
            "--host", 
            "0.0.0.0", 
            "--backed", 
            "--disable-annotations", 
            "--disable-gene-sets-save", 
            "/mountpoint-s3/data/cellxgene/pbmc3k.h5ad"
          ]
          ports:
          - containerPort: 8080
            protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 500Mi 
              cpu: 250m
          readinessProbe: # Block traffic to container if not ready
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60 
            failureThreshold: 10
          livenessProbe: # Restart container if not healthy
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 600  # 10min
            periodSeconds: 3600 # 1hr
            failureThreshold: 2
          volumeMounts:
            - name: mountpoint-s3
              mountPath: /mountpoint-s3
      volumes:
        - name: mountpoint-s3
          persistentVolumeClaim:
            claimName: s3-claim
      # run on big memory machine
      nodeSelector:
        workload: cellxgene
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "cellxgene"
          effect: "NoSchedule"
---
kind: Service
apiVersion: v1
metadata:
  namespace: cellxgene
  name: cellxgene-service-s3-access-example
  labels:  # For convenience
    app: cellxgene
    dataset: pbmc3k-test.h5ad
spec:
  selector:
    dataset: pbmc3k-test.h5ad
  ports:
    - port: 8080
