apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    ingress.kubernetes.io/proxy-connect-timeout: "300"
    ingress.kubernetes.io/proxy-read-timeout: "300"
    ingress.kubernetes.io/proxy-send-timeout: "300"
    # ingress.kubernetes.io/large-client-header-buffers: "4 32k"
    # increae max response size to avoid 413 errors see
    # https://github.com/kubernetes/ingress-nginx/issues/1824
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    ingress.kubernetes.io/proxy-body-size: 512m
    # add proxy protocol to header
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  name: cbioportal-ingress
spec:
  tls:
#  - hosts:
#    - webinar.cbioportal.org
#    secretName: webinar-cbio-cert
  - hosts:
    - genie.cbioportal.org
    secretName: geniepublic-cbio-cert
  - hosts:
    - genie-private.cbioportal.org
    secretName: genieprivate-cbio-cert
  - hosts:
    - www.cbioportal.org
    secretName: cbioportal-www-cert
  - hosts:
    - master.cbioportal.org
    secretName: master-cbio-cert
  - hosts:
    - beta.cbioportal.org
    secretName: cbioportal-beta-cert
#  - hosts:
#      - keycloak.cbioportal.org
#    secretName: keycloak-cert
#  - hosts:
#      - genie-public-beta.cbioportal.org
#    secretName: cbioportal-genie-public-beta-cert
#  - hosts:
#      - session-service.cbioportal.org
#    secretName: cbioportal-session-service-cert
#  session service beta is not in use for now, uncomment this to apply ingress for session-service-beta.cbioportal.org
#  - hosts:
#      - session-service-beta.cbioportal.org
#    secretName: cbioportal-session-service-cert
  rules:
#  - host: keycloak.cbioportal.org
#    http:
#      paths:
#        - path: /
#          pathType: Prefix
#          backend:
#            service:
#              name: keycloak-http
#              port:
#                number: 80
#  - host: webinar.cbioportal.org
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: cbioportal
#            port:
#              number: 80
#  - host: genie-public-beta.cbioportal.org
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: cbioportal-backend-genie-public-beta
#            port:
#              number: 80
  - host: genie.cbioportal.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cbioportal-backend-genie-public
            port:
              number: 80
  - host: genie-private.cbioportal.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cbioportal-backend-genie-private
            port:
              number: 80
  - host: www.cbioportal.org
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cbioportal
              port:
                number: 80
  - host: master.cbioportal.org
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cbioportal-backend-master
              port:
                number: 80
  - host: beta.cbioportal.org
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cbioportal-backend-beta
              port:
                number: 80
#  - host: session-service.cbioportal.org
#    http:
#      paths:
#        - path: /
#          pathType: Prefix
#          backend:
#            service:
#              name: cbioportal-session-service
#              port:
#                number: 80

#  session service beta is not in use for now, uncomment this to apply ingress for session-service-beta.cbioportal.org
#  - host: session-service-beta.cbioportal.org
#    http:
#      paths:
#        - path: /
#          pathType: Prefix
#          backend:
#            service:
#              name: cbioportal-session-service-beta
#              port:
#                number: 80
