apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # ingress.kubernetes.io/large-client-header-buffers: "4 32k"
    # increae max response size to avoid 413 errors see
    # https://github.com/kubernetes/ingress-nginx/issues/1824
    ingress.kubernetes.io/proxy-body-size: 512m
    ingress.kubernetes.io/proxy-connect-timeout: "300"
    ingress.kubernetes.io/proxy-read-timeout: "300"
    ingress.kubernetes.io/proxy-send-timeout: "300"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # add proxy protocol to header
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  name: cbioportal-ingress
  namespace: default
spec:
  rules:
  - host: keycloak.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal-keycloak-http
            port:
              number: 80
        path: /
        pathType: Prefix
#  - host: webinar.cbioportal.org
#    http:
#      paths:
#      - backend:
#          service:
#            name: cbioportal
#            port:
#              number: 80
#        path: /
#        pathType: Prefix
  - host: genie.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal-backend-genie-public-blue
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: genie-public-blue.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal-backend-genie-public-blue
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: genie-public-green.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal-backend-genie-public-green
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: genie-private.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal-backend-genie-private-blue
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: genie-private-blue.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal-backend-genie-private-blue
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: genie-private-green.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal-backend-genie-private-green
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: www.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: master.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal-backend-master
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: beta.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal-backend-beta
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: session-service.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal-session-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: crdc.cbioportal.org
    http:
      paths:
      - backend:
          service:
            name: cbioportal-backend-nci
            port:
              number: 80
        path: /
        pathType: Prefix
#  session service beta is not in use for now, uncomment this to apply ingress for session-service-beta.cbioportal.org
#  - host: session-service-beta.cbioportal.org
#    http:
#      paths:
#      - backend:
#          service:
#            name: cbioportal-session-service-beta
#            port:
#              number: 80
#        path: /
#        pathType: Prefix
  tls:
#  - hosts:
#    - webinar.cbioportal.org
#    secretName: webinar-cbio-cert
  - hosts:
    - genie.cbioportal.org
    secretName: geniepublic-cbio-cert
  - hosts:
    - genie-public-blue.cbioportal.org
    secretName: geniepublicblue-cbio-cert
  - hosts:
    - genie-public-green.cbioportal.org
    secretName: geniepublicgreen-cbio-cert
  - hosts:
    - genie-private.cbioportal.org
    secretName: genieprivate-cbio-cert
  - hosts:
    - genie-private-blue.cbioportal.org
    secretName: genieprivateblue-cbio-cert
  - hosts:
    - genie-private-green.cbioportal.org
    secretName: genieprivategreen-cbio-cert
  - hosts:
    - www.cbioportal.org
    secretName: cbioportal-www-cert
  - hosts:
    - master.cbioportal.org
    secretName: master-cbio-cert
  - hosts:
    - beta.cbioportal.org
    secretName: cbioportal-beta-cert
  - hosts:
    - keycloak.cbioportal.org
    secretName: keycloak-cert
  - hosts:
    - crdc.cbioportal.org
    secretName: cbioportal-crdc-cert
  - hosts:
    - session-service.cbioportal.org
    secretName: cbioportal-session-service-cert
#  session service beta is not in use for now, uncomment this to apply ingress for session-service-beta.cbioportal.org
#  - hosts:
#      - session-service-beta.cbioportal.org
#    secretName: cbioportal-session-service-cert
