apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: cbioportal:apps/Deployment:default/eks-msk-beta-offline
  labels:
    app.kubernetes.io/instance: cbioportal
    run: eks-msk-beta-offline
  name: eks-msk-beta-offline
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eks-msk-beta-offline
  template:
    metadata:
      labels:
        run: eks-msk-beta-offline
    spec:
      containers:
        - name: eks-msk-beta-offline
          image: cbioportal/cbioportal:mskcc-beta-portal-offline-2025-10-13
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: 16Mi
            limits:
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      nodeSelector:
        workload: cbioportal
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "cbioportal"
          effect: "NoSchedule"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: cbioportal:/Service:default/eks-msk-beta-offline
  labels:
    run: eks-msk-beta-offline
  name: eks-msk-beta-offline
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    run: eks-msk-beta-offline
  type: ClusterIP
