apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: eks-cdd-graphite
  name: eks-cdd-graphite
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eks-cdd-graphite
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: eks-cdd-graphite
    spec:
      volumes:
      - name: cdd-ssl-volume
        secret:
          secretName: cdd-ssl-graphite
          defaultMode: 0600
          items:
          - key: oncotree_graphite_private_key_ecdsa1
            path: graphite-ssl-key
      - name: cdd-cache
        persistentVolumeClaim:
          claimName: cdd-graphite-pvc
      containers:
      - envFrom:
        - secretRef:
            name: cdd-eks-graphite
        image: cbioportal/cdd:json-workaround-20260225
        command: ["/bin/sh", "-c"]
        args: ["java -XX:+StartAttachListener -Xmx700m -Dslack.url=$(SLACK_URL) -jar cdd.jar"]
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /swagger-ui.html 
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 5
          failureThreshold: 10
        name: cdd
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: "/data/ehcache/"
          name: cdd-cache
        - name: cdd-ssl-volume
          mountPath: "/cdd-ssl-graphite/graphite-ssl-key"
          subPath: graphite-ssl-key
        resources:
          requests:
              cpu: 100m
              memory: 1Gi
          limits:
              memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # run on big memory machine
      nodeSelector:
        workload: cdd
      tolerations:
        - key: workload
          operator: Equal
          value: cdd
          effect: NoSchedule
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: eks-cdd-graphite
  name: eks-cdd-graphite
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    run: eks-cdd-graphite
  type: ClusterIP
