apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: eks-msk-beta
  name: eks-msk-beta
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/eks-msk-beta
spec:
  replicas: 2
  selector:
    matchLabels:
      run: eks-msk-beta
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: eks-msk-beta
    spec:
      volumes:
      - name: msk-beta-eks-configmap-volume
        configMap:
          name: msk-beta-spring-boot-kc
          items:
          - key: local.key
            path: local.key
          - key: local.crt
            path: local.crt
      - name: cbioportal-frontend-config-volume
        configMap:
          name: msk-eks-frontend-config
      containers:
      - envFrom:
        - configMapRef:
            name: msk-beta-eks
        env:
        - name: PORTAL_HOME
          value: /cbioportal/
        image: cbioportal/cbioportal:master-web-shenandoah
        volumeMounts:
        - name: msk-beta-eks-configmap-volume
          mountPath: /cbioportal/local.key
          subPath: local.key
        - name: msk-beta-eks-configmap-volume
          mountPath: /cbioportal/local.crt
          subPath: local.crt
        - name: cbioportal-frontend-config-volume
          mountPath: /cbioportal/aaron.json
        command: [ "java" ]
        args: [
            # from https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/
            "-Xms100m",
            "-Xmx60g",
            "-XX:+UnlockExperimentalVMOptions",
            "-XX:+UseShenandoahGC",
            "-XX:ShenandoahUncommitDelay=1000",
            "-XX:ShenandoahGuaranteedGCInterval=10000",
            #"-XX:+AlwaysPreTouch",
            #"-XX:+UseTransparentHugePages",
            #"-XX:+UseNUMA",
            #"-XX:+PrintGCDetails",
            #"-XX:+UseParallelGC",
            #"-XX:+PrintGCDateStamps",
            #"-XX:ParallelGCThreads=4",
            #"-XX:+UseG1GC",
            #"-XX:+AggressiveHeap",
            # non aggressive garbage collection
            #"-XX:MinHeapFreeRatio=20",
            #"-XX:MaxHeapFreeRatio=40",
            #"-XX:GCTimeRatio=19",
            #"-XX:AdaptiveSizePolicyWeight=90",
            # This issue says to use maxRAMFraction > 1
            # https://github.com/akka/akka/issues/23499, but haven't found this
            # to work v well
            #"-XX:MaxRAMFraction=1",
            "-XX:+PrintFlagsFinal",
            "-XshowSettings:vm",
            "-jar",
            "/cbioportal-webapp/app.jar",
            # handles legacy swagger urls after upgrade
            "--springdoc.swagger-ui.disable-swagger-default-url=true",
            "--springdoc.swagger-ui.path=/api/swagger-ui",
            "--springdoc.api-docs.path=/api/v3/api-docs",
            # enable remote debug
            "--com.sun.management.jmxremote.rmi.port=8849",
            "--com.sun.management.jmxremote=false",
            "--com.sun.management.jmxremote.port=8849",
            "--com.sun.management.jmxremote.ssl=false",
            "--com.sun.management.jmxremote.authenticate=false",
            "--com.sun.management.jmxremote.local.only=false",
            "--java.rmi.server.hostname=localhost",
            # /enable remote debug
            "--frontend.url=https://deploy-preview-4790--cbioportalfrontend.netlify.app/",
            "--default_cross_cancer_study_session_id=5c8a7d55e4b046111fee2296",
            "--quick_search.enabled=true",
            "--about=about_us.html",
            "--enable_cross_study_expression=(studies)=>studies.filter(s=>/pan_can_atlas/.test(s.studyId) === false).length === 0",
            "--default_cross_cancer_study_list=mskimpact",
            "--faq=faq_tcga.html",
            "--news=news_tcga.html",
            "--skin.footer=",
            "--skin.right_nav.whats_new_blurb=",
            "--skin.quick_select_buttons=TCGA PanCancer Atlas Studies#*pan_can_atlas*;Curated set of non-redundant studies|185 studies that are manually curated including TCGA and non-TCGA studies with no overlapping samples#acbc_mskcc_2015,acc_tcga_pan_can_atlas_2018,acyc_fmi_2014,acyc_mda_2015,acyc_mskcc_2013,acyc_sanger_2013,all_phase2_target_2018_pub,all_stjude_2016,aml_target_2018_pub,ampca_bcm_2016,angs_project_painter_2018,bfn_duke_nus_2015,blca_bgi,blca_cornell_2016,blca_dfarber_mskcc_2014,blca_mskcc_solit_2012,blca_mskcc_solit_2014,blca_tcga_pan_can_atlas_2018,brca_bccrc,brca_broad,brca_igr_2015,brca_mbcproject_wagle_2017,brca_metabric,brca_sanger,brca_tcga_pan_can_atlas_2018,ccrcc_irc_2014,ccrcc_utokyo_2013,cesc_tcga_pan_can_atlas_2018,chol_jhu_2013,chol_nccs_2013,chol_nus_2012,chol_tcga_pan_can_atlas_2018,cll_iuopa_2015,cllsll_icgc_2011,coadread_dfci_2016,coadread_genentech,coadread_mskcc,coadread_tcga_pan_can_atlas_2018,cscc_dfarber_2015,cscc_hgsc_bcm_2014,ctcl_columbia_2015,desm_broad_2015,dlbc_tcga_pan_can_atlas_2018,dlbcl_dfci_2018,dlbcl_duke_2017,egc_tmucih_2015,es_dfarber_broad_2014,es_iocurie_2014,esca_broad,esca_tcga_pan_can_atlas_2018,escc_icgc,escc_ucla_2014,gbc_shanghai_2014,gbm_tcga_pan_can_atlas_2018,glioma_msk_2018,hcc_inserm_fr_2015,hcc_msk_venturaa_2018,hnsc_broad,hnsc_jhu,hnsc_mdanderson_2013,hnsc_tcga_pan_can_atlas_2018,kich_tcga_pan_can_atlas_2018,kirc_bgi,kirc_tcga_pan_can_atlas_2018,kirp_tcga_pan_can_atlas_2018,laml_tcga_pan_can_atlas_2018,lcll_broad_2013,lgg_tcga_pan_can_atlas_2018,lgg_ucsf_2014,liad_inserm_fr_2014,lihc_amc_prv,lihc_riken,lihc_tcga_pan_can_atlas_2018,luad_broad,luad_tcga_pan_can_atlas_2018,luad_tsp,lusc_tcga_pan_can_atlas_2018,mbl_broad_2012,mbl_pcgp,mbl_sickkids_2016,mcl_idibips_2013,mds_tokyo_2011,mel_tsam_liang_2017,meso_tcga_pan_can_atlas_2018,mixed_allen_2018,mixed_pipseq_2017,mm_broad,mpnst_mskcc,mrt_bcgsc_2016,msk_impact_2017,nbl_amc_2012,nbl_target_2018_pub,nbl_ucologne_2015,nccrcc_genentech_2014,nepc_wcm_2016,nhl_bcgsc_2011,nhl_bcgsc_2013,npc_nusingapore,nsclc_unito_2016,ov_tcga_pan_can_atlas_2018,paac_jhu_2014,paad_qcmg_uq_2016,paad_tcga_pan_can_atlas_2018,paad_utsw_2015,pact_jhu_2011,panet_arcnet_2017,panet_jhu_2011,panet_shanghai_2013,pcnsl_mayo_2015,pcpg_tcga_pan_can_atlas_2018,pediatric_dkfz_2017,plmeso_nyu_2015,prad_broad,prad_eururol_2017,prad_fhcrc,prad_mich,prad_mpcproject_2018,prad_mskcc,prad_mskcc_cheny1_organoids_2014,prad_tcga_pan_can_atlas_2018,rms_nih_2014,rt_target_2018_pub,sarc_mskcc,sarc_tcga_pan_can_atlas_2018,scco_mskcc,sclc_cancercell_gardner_2017,sclc_jhu,sclc_ucologne_2015,skcm_broad,skcm_broad_brafresist_2012,skcm_tcga_pan_can_atlas_2018,skcm_vanderbilt_mskcc_2015,skcm_yale,stad_pfizer_uhongkong,stad_tcga_pan_can_atlas_2018,stad_utokyo,summit_2018,tet_nci_2014,tgct_tcga_pan_can_atlas_2018,thca_tcga_pan_can_atlas_2018,thym_tcga_pan_can_atlas_2018,uccc_nih_2017,ucec_tcga_pan_can_atlas_2018,ucs_jhu_2014,ucs_tcga_pan_can_atlas_2018,um_qimr_2016,urcc_mskcc_2016,utuc_mskcc_2015,uvm_tcga_pan_can_atlas_2018,vsc_cuk_2018,wt_target_2018_pub,acyc_jhu_2016,prostate_dkfz_2018,histiocytosis_cobi_msk_2019,utuc_cornell_baylor_mdacc_2019,prad_su2c_2019,cll_broad_2015,coad_cptac_2019,brca_mskcc_2019,acc_2019,pptc_2019,prad_msk_2019,ccrcc_dfci_2019,mpn_cimr_2013,nsclc_tracerx_2017,mnm_washu_2016,bcc_unige_2016,coad_caseccc_2015,metastatic_solid_tumors_mich_2017,aml_ohsu_2018,ihch_smmu_2014,nsclc_mskcc_2018,skcm_dfci_2015,skcm_mskcc_2014,mel_ucla_2016,utuc_msk_2019,gbm_columbia_2019,stad_oncosg_2018,brca_smc_2018,luad_oncosg_2020,angs_painter_2020,mel_dfci_2019,lung_smc_2016,utuc_igbmc_2021",
            "--skin.example_study_queries=tcga pancancer atlas\ntcga -legacy -pancancer\ntcga or icgc\nmsk-impact\n-\"cell line\"\nbreast\nesophageal OR stomach\nprostate msk\nserous",
            "--skin.examples_right_column_html=<ul>  <li>    <a href=\"index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit\">RAS/RAF alterations in colorectal cancer</a>  </li>  <li>    <a href=\"index.do?tab_index=tab_visualize&cancer_study_list=ov_tcga_pub&cancer_study_id=ov_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ov_tcga_pub_mutations&Z_SCORE_THRESHOLD=2.0&case_set_id=ov_tcga_pub_3way_complete&case_ids=&gene_list=BRCA1+BRCA2&gene_set_choice=user-defined-list&Action=Submit#mutation_details\">BRCA1 and BRCA2 mutations in ovarian cancer</a>  </li>  <li>    <a href=\"index.do?cancer_study_list=ucec_tcga_pub&cancer_study_id=ucec_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ucec_tcga_pub_mutations&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=ucec_tcga_pub_sequenced&case_ids=&gene_set_choice=user-defined-list&gene_list=POLE%3A+MUT+%3D+P286+MUT+%3D+V411+MUT+%3D+L424+MUT+%3D+S297F&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit\">POLE hotspot mutations in endometrial cancer</a>  </li>  <li>    <a href=\"index.do?case_set_id=gbm_tcga_pub_sequenced&tab_index=tab_visualize&Action=Submit&genetic_profile_ids=gbm_tcga_pub_mutations&genetic_profile_ids=gbm_tcga_pub_cna_rae&case_ids=&Z_SCORE_THRESHOLD=1.0&cancer_study_list=gbm_tcga_pub&cancer_study_id=gbm_tcga_pub&gene_list=TP53+MDM2+MDM4&gene_set_choice=user-defined_list&Action=Submit#summary\">TP53 and MDM2/4 alterations in GBM</a>  </li>  <li>    <a href=\"index.do?case_set_id=gbm_tcga_pub_sequenced&tab_index=tab_download&Action=Submit&genetic_profile_ids=gbm_tcga_pub_mutations&cancer_study_list=gbm_tcga_pub&cancer_study_id=gbm_tcga_pub&gene_list=PTEN&gene_set_choice=user-defined_list&transpose_matrix=on\">PTEN mutations in GBM in text format</a>  </li>  <li>    <a href=\"ln?q=BRAF:MUT=V600E\">BRAF V600E mutations across cancer types</a>  </li>  <li>    <a href=\"case.do#/patient?studyId=ucec_tcga_pub&caseId=TCGA-BK-A0CC\">Patient view of an endometrial cancer case</a>  </li></ul>",
            "--skin.patientview.filter_genes_profiled_all_samples=false",
            "--skin.right_logo=msk_logo_transparent_black.png",
            "--skin.right_nav.show_testimonials=true",
            "--skin.title=MSK cBioPortal (Beta)",
            "--installation_map_url=https://installationmap.netlify.app/",
            "--app.name=cbioportal-msk-beta",
            # connecting over dbcp
            "--dbconnector=dbcp",
            "--authenticate=saml",
            "--authorization=false",
            "--security.cors.allowed-origins=*",
            "--db.user=$(DB_USER)",
            "--db.password=$(DB_PASSWORD)",
            "--db.suppress_schema_version_mismatch_errors=true",
#            "-Ddb.host=$(DB_HOST)",
#            "-Ddb.portal_db_name=$(DB_PORTAL_DB_NAME)",
            "--spring.datasource.driver-class-name=com.mysql.jdbc.Driver",
            "--spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect",
            "--spring.datasource.url=jdbc:mysql://$(DB_HOST):3306/$(DB_PORTAL_DB_NAME)?zeroDateTimeBehavior=convertToNull&useSSL=false",
            "--spring.datasource.username=$(DB_USER)",
            "--spring.datasource.password=$(DB_PASSWORD)",
            "--tomcat.catalina.scope=runtime",
            "--show.transcript_dropdown=true",
            "--show.civic=$(SHOW_CIVIC)",
            "--skin.show_tweet_button=$(SKIN_SHOW_TWEET_BUTTON)",
            "--skin.email_contact=cbioportal@cbioportal.org",
            "--skin.data_sets_footer=Data sets of TCGA studies were downloaded from Broad Firehose (http://gdac.broadinstitute.org) and updated monthly. In some studies, data sets were from the working groups directly.",
            "--skin.data_sets_header=The portal currently contains data from the following cancer genomics studies and MSKCC internal studies.  The table below lists the number of available samples per cancer study and data type.",
            "--skin.authorization_message=Access to this portal is only available to authorized users.",
            "--skin.blurb=<p>Please adhere to the <a href=\"https://cmo.mskcc.org/index.php/msk-impact/\">MSK-IMPACT publication guidelines</a> when using MSK-IMPACT DATA in your publications.</p> <p>When writing manuscripts, please do not include private links to this portal.</p> <p><b>Please cite</b> <a href=\"http://www.ncbi.nlm.nih.gov/pubmed/23550210\">Gao et al. <i>Sci. Signal.</i> 2013</a> &amp;  <a href=\"http://cancerdiscovery.aacrjournals.org/content/2/5/401.abstract\"> Cerami et al. <i>Cancer Discov.</i> 2012</a> when publishing results based on cBioPortal.</p>",
            "--show.mdacc.heatmap=true",
            "--priority_studies=Shared institutional Data Sets#mskimpact,mskarcher,cellline_mskcc,mixed_cbe_solitd_MSK_cfDNA_IMPACT,mixed_impact_wes_2017,msk_impact_ch_2020",
            #"-Dsession.service.url=https://session-service.cbioportal.org/api/sessions/msk_portal/",
            "--session.service.url=https://session-service.cbioportal.org/api/sessions/hgnc_1938_portal/",
            "--session.service.origin=*",
            "--session.service.user=$(SESSION_SERVICE_USER_NAME)",
            "--session.service.password=$(SESSION_SERVICE_USER_PASSWORD)",
            "--google_analytics_profile_id=$(GOOGLE_ANALYTICS_PROFILE_ID)",
            "--googleplus.consumer.key=$(GOOGLE_PLUS_CONSUMER_KEY)",
            "--googleplus.consumer.secret=$(GOOGLE_PLUS_CONSUMER_SECRET)",
            "--microsoftlive.consumer.key=$(MICROSOFT_LIVE_CONSUMER_KEY)",
            "--microsoftlive.consumer.secret=$(MICROSOFT_LIVE_CONSUMER_SECRET)",
            "--bitly.url=$(BITLY_URL)",
            "--bitly.access.token=$(BITLY_ACCESS_TOKEN)",
            "--sentry.dsn=$(SENTRY_DSN)",
            "--frontend.config=/cbioportal/aaron.json",
            "--sentry.factory=org.cbioportal.logging.SentryClientFactory",
            #"-Dsentryjs.frontend_project_endpoint=$(SENTRY_FRONTEND_DSN)",
            "--sitemaps=false",
            "--oncokb.public_api.url=https://core.oncokb.aws.mskcc.org/api/v1",
            # token is not needed to access MSK OncoKB instance
            "--oncokb.token=fake_token",
            #"--oncokb.merge_icons_by_default=false",
            "--genomenexus.url=https://v1.genomenexus.org",
            "--show.genomenexus.annotation_sources=mutation_assessor",
            "--matchminer.url=http://ec2-54-158-52-176.compute-1.amazonaws.com:5555",
            "--matchminer.token=$(MATCHMINER_TOKEN)",
            "--filter_groups_by_appname=false",
            # redis session store settings (different from redis persistence cache)
            "--spring.session.store-type=redis",
            "--spring.data.redis.host=$(REDIS_SESSION_HOST)",
            "--spring.data.redis.port=$(REDIS_SESSION_PORT)",
            "--spring.data.redis.password=$(REDIS_SESSION_PASSWORD)",
            # To enable redis session store, we need to set
            # spring.autoconfigure.exclude to a random value to override the
            # property in applications.properties.EXAMPLE
            "--spring.autoconfigure.exclude=dontexcludeanythingplz",
            # cache settings (currently redis)
#            "-Dcache.statistics_endpoint_enabled=false",
            "--redis.database=3",
            "--persistence.cache_type=redis",
#            "--redis.leader_address=redis://cbioportal-persistence-redis-master:6379",
#            "--redis.follower_address=redis://cbioportal-persistence-redis-replicas:6379",
            "--redis.leader_address=redis://eks-msk-persistence-redis-master:6379",
            "--redis.follower_address=redis://eks-msk-persistence-redis-replicas:6379",
            "--redis.password=$(REDIS_PASSWORD)",
            "--ehcache.cache_type=none",
            "--cache.endpoint.api-key=$(CACHE_API_KEY)",
            "--cache.endpoint.enabled=true",
            "--redis.clear_on_startup=false",
            # misc frontend settings (this is NOT for backend persistence layer caching)
            "--enable_persistent_cache=false",
            # auth
            # "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.assertingparty.metadata-uri=/cbioportal/msk-beta-cbioportal-saml-idp-metadata.xml",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.assertingparty.metadata-uri=https://keycloak.cbioportal.mskcc.org/auth/realms/msk/protocol/saml/descriptor",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.entity-id=cbioportal-msk-beta-v6",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.signing.credentials[0].certificate-location=file:/cbioportal/local.crt",
            "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.signing.credentials[0].private-key-location=file:/cbioportal/local.key",
            # "--logging.level.org.springframework.security=DEBUG",
            # "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.singlelogout.binding=POST",
            # "--spring.security.saml2.relyingparty.registration.cbio-saml-idp.singlelogout.response-url=http://localhost:8080/logout/saml2/slo",
            # compress on client side
            "--enable_request_body_gzip_compression=true",
            "--server.compression.enabled=true",
            "--server.tomcat.connection-timeout=20000",
            "--server.tomcat.max-http-response-header-size=16384",
            "--server.max-http-request-header-size=16384",
            "--server.port=8888",
        ]
        imagePullPolicy: Always
#        readinessProbe:
#          httpGet:
#            path: /api/health
#            port: 8888
#          initialDelaySeconds: 45
#          timeoutSeconds: 1
#          periodSeconds: 5
#          failureThreshold: 3
#        livenessProbe:
#          httpGet:
#            path: /api/health
#            port: 8888
#          initialDelaySeconds: 180
#          timeoutSeconds: 1
#          periodSeconds: 12
#          failureThreshold: 5
        name: eks-msk-beta
        ports:
        - containerPort: 8888
          protocol: TCP
        - containerPort: 8849
          protocol: TCP
        resources:
          requests:
            memory: 30Gi
          limits:
            memory: 60Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: msk-beta-temporary
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "msk-beta-temporary"
          effect: "NoSchedule"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: eks-msk-beta
  name: eks-msk-beta
  selfLink: /api/v1/namespaces/default/services/eks-msk-beta
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    run: eks-msk-beta
  type: ClusterIP
