apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: eks-immunotherapy
  name: eks-immunotherapy
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/eks-immunotherapy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eks-immunotherapy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: eks-immunotherapy
    spec:
      volumes:
      - name: immunotherapy-eks-configmap-volume
        configMap:
          name: cbioportal-immunotherapy-kc
          items:
          - key: portal.properties
            path: portal.properties
          - key: immunotherapy-cbioportal-saml-idp-metadata.xml
            path: immunotherapy-cbioportal-saml-idp-metadata.xml
          - key: cbioportal-saml-keystore.jks
            path: cbioportal-saml-keystore.jks
      containers:
      - envFrom:
        - configMapRef:
            name: immunotherapy-eks
        env:
        - name: PORTAL_HOME
          value: /cbioportal/
        image: cbioportal/cbioportal:3.7.1-web-shenandoah
        volumeMounts:
        - name: immunotherapy-eks-configmap-volume
          mountPath: /cbioportal/portal.properties
          subPath: portal.properties
        - name: immunotherapy-eks-configmap-volume
          mountPath: /cbioportal/immunotherapy-cbioportal-saml-idp-metadata.xml
          subPath: immunotherapy-cbioportal-saml-idp-metadata.xml
        - name: immunotherapy-eks-configmap-volume
          mountPath: /cbioportal/cbioportal-saml-keystore.jks
          subPath: cbioportal-saml-keystore.jks
        command: [ "/usr/bin/java" ]
        args: [
            # from https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/
            "-Xms100m",
            "-Xmx15g",
            "-XX:+UnlockExperimentalVMOptions",
            "-XX:+UseShenandoahGC",
            "-XX:ShenandoahUncommitDelay=1000",
            "-XX:ShenandoahGuaranteedGCInterval=10000",
            #"-XX:+AlwaysPreTouch",
            #"-XX:+UseTransparentHugePages",
            #"-XX:+UseNUMA",
            #"-XX:+PrintGCDetails",
            #"-XX:+UseParallelGC",
            #"-XX:+PrintGCDateStamps",
            #"-XX:ParallelGCThreads=4",
            #"-XX:+UseG1GC",
            #"-XX:+AggressiveHeap",
            # non aggressive garbage collection
            #"-XX:MinHeapFreeRatio=20",
            #"-XX:MaxHeapFreeRatio=40",
            #"-XX:GCTimeRatio=19",
            #"-XX:AdaptiveSizePolicyWeight=90",
            # This issue says to use maxRAMFraction > 1
            # https://github.com/akka/akka/issues/23499, but haven't found this
            # to work v well
            #"-XX:MaxRAMFraction=1",
            "-XX:+PrintFlagsFinal",
            "-XshowSettings:vm",
            # need to set MaxRAM, somehow the MaxRAMFraction is not picked up
            # from the limits
            #"-XX:MaxRAM=6500m",
            # enable remote debug
            "-Dfilter_groups_by_appname=false",
            "-Dcom.sun.management.jmxremote.rmi.port=8849",
            "-Dcom.sun.management.jmxremote=false",
            "-Dcom.sun.management.jmxremote.port=8849",
            "-Dcom.sun.management.jmxremote.ssl=false",
            "-Dcom.sun.management.jmxremote.authenticate=false",
            "-Dcom.sun.management.jmxremote.local.only=false",
            "-Djava.rmi.server.hostname=localhost",
            "-Dquick_search.enabled=true",
            "-Dskin.footer=",
            "-Dskin.right_nav.whats_new_blurb=",
            "-Dskin.example_study_queries=tcga pancancer atlas\ntcga -legacy -pancancer\ntcga or icgc\nmsk-impact\n-\"cell line\"\nbreast\nesophageal OR stomach\nprostate msk\nserous",
            "-Dpriority_studies=PanCancer Studies#sclc_mskimpact_2017,msk_impact_2017,metastatic_solid_tumors_mich_2017,mixed_allen_2018,summit_2018,tmb_mskcc_2018,ntrk_msk_2019,msk_ch_2020;Pediatric Cancer Studies#pptc_2019,all_phase2_target_2018_pub,rt_target_2018_pub,wt_target_2018_pub,aml_target_2018_pub,nbl_target_2018_pub,pediatric_dkfz_2017,mixed_pipseq_2017,all_stjude_2016,all_stjude_2015,es_dfarber_broad_2014,es_iocurie_2014,mbl_pcgp;Immunogenomic Studies#gbm_columbia_2019,skcm_dfci_2015,skcm_mskcc_2014,mel_ucla_2016,nsclc_mskcc_2018,nsclc_mskcc_2015,tmb_mskcc_2018,ccrcc_dfci_2019;Cell lines#ccle_broad_2019,cellline_ccle_broad,cellline_nci60",
            "-Dskin.patientview.filter_genes_profiled_all_samples=false",
            "-Dinstallation_map_url=https://installationmap.netlify.app/",
            "-Dapp.name=eks-immunotherapy",
            # connecting over dbcp
            "-Ddbconnector=dbcp",
            "-Dauthenticate=saml",
            "-Dauthorization=false",
            "-Ddb.user=$(DB_USER)",
            "-Ddb.password=$(DB_PASSWORD)",
            "-Ddb.host=$(DB_HOST)",
            "-Ddb.connection_string=$(DB_CONNECTION_STRING)",
            "-Ddb.portal_db_name=cgds_gdac",
            #"-Dtomcat.catalina.scope=runtime",
            "-Dshow.transcript_dropdown=true",
            "-Dshow.civic=$(SHOW_CIVIC)",
            "-Dskin.show_tweet_button=$(SKIN_SHOW_TWEET_BUTTON)",
            "-Dskin.email_contact=cbioportal@googlegroups.com",
            "-Dskin.data_sets_footer=Data sets of published studies were curated from literature. Data sets of legacy TCGA studies were downloaded from the <a href=\"http://gdac.broadinstitute.org\">Broad Institute Firehose</a>, last updated 1/28/2016.",
            "-Dskin.data_sets_header=The table below lists the number of available samples per cancer study and data type.",
            "-Dskin.authorization_message=Welcome to cBioPortal. Logging in will allow you to access your studies and groups from any computer, and cBioPortal will also remember your study view charts preferences for each study (i.e. order of the charts, type of charts and visibility). Login is optional and not required to access any of the other features of cBioPortal.",
            "-Dskin.blurb=",
            "-Dshow.mdacc.heatmap=true",
            "-Dsession.service.url=https://session-service.cbioportal.aws.mskcc.org/api/sessions/immunotherapy_portal/",
            "-Dsession.service.origin=*",
            "-Dsession.service.user=$(SESSION_SERVICE_USER_NAME)",
            "-Dsession.service.password=$(SESSION_SERVICE_USER_PASSWORD)",
            "-Dgoogle_analytics_profile_id=$(GOOGLE_ANALYTICS_PROFILE_ID)",
            "-Dgoogleplus.consumer.key=$(GOOGLE_PLUS_CONSUMER_KEY)",
            "-Dgoogleplus.consumer.secret=$(GOOGLE_PLUS_CONSUMER_SECRET)",
            "-Dmicrosoftlive.consumer.key=$(MICROSOFT_LIVE_CONSUMER_KEY)",
            "-Dmicrosoftlive.consumer.secret=$(MICROSOFT_LIVE_CONSUMER_SECRET)",
            "-Dbitly.url=$(BITLY_URL)",
            "-Dbitly.access.token=$(BITLY_ACCESS_TOKEN)",
            "-Dsentry.dsn=$(SENTRY_DSN)",
            "-Dsentry.factory=org.cbioportal.logging.SentryClientFactory",
            #"-Dsentryjs.frontend_project_endpoint=$(SENTRY_FRONTEND_DSN)",
            "-Ddb.suppress_schema_version_mismatch_errors=true",
            "-Dsitemaps=true",
            "-Doncokb.public_api.url=https://www.oncokb.org/api/v1",
            "-Doncokb.token=$(ONCOKB_TOKEN)",
            "-Dgenomenexus.url=https://v1.genomenexus.org",
            "-Dmatchminer.url=http://ec2-54-158-52-176.compute-1.amazonaws.com:5555",
            "-Dmatchminer.token=$(MATCHMINER_TOKEN)",
            # cache settings (currently redis)
#            "-Dcache.statistics_endpoint_enabled=false",
            "-Dpersistence.cache_type=none",
#           "-Dredis.leader_address=redis://cbioasdfportal-persistence-redis-master:6379",
#           "-Dredis.follower_address=redis://abccbioportal-persistence-redis-master:6379",
#           "-Dredis.database=97",
#           "-Dredis.password=$(REDIS_PASSWORD)",
#           "-Dehcache.cache_type=none",
            # misc frontend settings (this is NOT for backend persistence layer caching)
            "-Denable_persistent_cache=false",
            # compress on client side
            "-Denable_request_body_gzip_compression=true",
            "-jar",
            "/webapp-runner.jar",
            # this addresses same issue as
            # https://github.com/cBioPortal/cbioportal/issues/2328 one needs to
            # set this if one doesn't want to forward https -> http -> https
            # when logging in through google auth. Somehow this goes over http
            # otherwise.
            "--proxy-base-url",
            "https://immunotherapy.cbioportal.aws.mskcc.org:443",
            "--max-threads",
            "0",
            "--session-store",
            "redis",
            "--session-store-operation-timeout",
            "10000",
            # Fix long URL https://github.com/cBioPortal/cbioportal/issues/5836
            "-AmaxHttpHeaderSize=16384",
            "-AconnectionTimeout=20000",
            "--enable-compression",
            "--port",
            "8888",
            "/app.war"
        ]
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8888
          initialDelaySeconds: 45
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 180
          timeoutSeconds: 1
          periodSeconds: 12
          failureThreshold: 5
        name: eks-immunotherapy
        ports:
        - containerPort: 8888
          protocol: TCP
        - containerPort: 8849
          protocol: TCP
        resources:
          requests:
              cpu: 1500m
              memory: 4Gi
          limits:
              memory: 8Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: msk-cbioportal
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: eks-immunotherapy
  name: eks-immunotherapy
  selfLink: /api/v1/namespaces/default/services/eks-immunotherapy
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    run: eks-immunotherapy
  type: ClusterIP
