apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oncokb-ingress
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
spec:
  tls:
    - hosts:
      - www.oncokb.aws.mskcc.org
      - core.oncokb.aws.mskcc.org
      - germline-v2-core.oncokb.aws.mskcc.org
      - cbx.oncokb.aws.mskcc.org
      - pub-data-17.oncokb.aws.mskcc.org
      - data-legacy.oncokb.aws.mskcc.org
      - airflow.oncokb.aws.mskcc.org
  rules:
    - host: "www.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-public
                port:
                  number: 9095
    - host: "core.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-core
                port:
                  number: 8888
    - host: "germline-v2-core.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-core-germline-v2
                port:
                  number: 8888
    - host: "cbx.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-core-cbx
                port:
                  number: 8888
    - host: "pub-data-17.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-core-pub-data-2017
                port:
                  number: 8888
    - host: "data-legacy.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-core-data-legacy
                port:
                  number: 8888
    - host: "airflow.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-airflow-web
                port:
                  number: 8080
  ingressClassName: nginx
