apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oncokb-ingress
  namespace: oncokb
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    ingress.kubernetes.io/proxy-connect-timeout: "300"
    ingress.kubernetes.io/proxy-read-timeout: "300"
    ingress.kubernetes.io/proxy-send-timeout: "300"
    # ingress.kubernetes.io/large-client-header-buffers: "4 32k"
    # increae max response size to avoid 413 errors see
    # https://github.com/kubernetes/ingress-nginx/issues/1824
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    ingress.kubernetes.io/proxy-body-size: 512m
    # add proxy protocol to header
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
spec:
  tls:
  - hosts:
    - oncokb.org
    - www.oncokb.org
    - beta.oncokb.org
    - legacy.oncokb.org
    - test.oncokb.org
    - demo.oncokb.org
    - sop.oncokb.org
    - msk.oncokb.org
    - fda.oncokb.org
    - public.api.oncokb.org
    - transcript.oncokb.org
    secretName: oncokb-cert
  rules:
  - host: oncokb.org
    http:
      paths:
      - path: /
        backend:
          # we still cannot point to oncokb-public yet since there are lots of portal installations are pointing to that
          serviceName: oncokb-core-legacy
          servicePort: http
  - host: www.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-public
          servicePort: http
  - host: beta.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-public-beta
          servicePort: http
  - host: demo.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-core-demo
          servicePort: http
  - host: test.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-public-test
          servicePort: http
  - host: legacy.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-core-legacy
          servicePort: http
  - host: sop.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-sop
          servicePort: http
  - host: msk.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-public
          servicePort: http
  - host: fda.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-public-fda
          servicePort: http
  - host: transcript.oncokb.org
    http:
      paths:
        - path: /
          backend:
            serviceName: oncokb-transcript
            servicePort: http
  - host: public.api.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-core-public
          servicePort: http
