## Configure Git to pull dags and plugins
git:
  dags:
    enabled: true
    repositories:
      # More information on getting DAG files from GitHub:
      # https://github.com/bitnami/charts/tree/main/bitnami/airflow#option-2-get-your-dag-files-from-a-git-repository
      - repository: https://oncokbdev:${ONCOKBDEV_PRIVATE_ACCESS_TOKEN}@github.com/oncokb/oncokb-pipeline
        branch: master
        name: oncokb-airflow-dags
        path: /oncokb-airflow
  clone:
    # Airflow runs an initContainer to clone the repository
    extraEnvVarsCM: oncokb-github
  sync:
    # By default airflow syncs with the repo every 60s.
    extraEnvVarsCM: oncokb-github

auth:
  username: admin

serviceAccount:
  name: "oncokb-airflow-service-account"

extraEnvVars:
  # Passing this to PYTHONPATH helps resolve some import errors in python files.
  - name: PYTHONPATH
    value: "/opt/bitnami/airflow/dags/git_oncokb-airflow-dags/"
  # Specify which folder to look for Airflow DAGs. For MSK cluster use msk-dag folder.
  - name: AIRFLOW__CORE__DAGS_FOLDER
    value: "opt/bitnami/airflow/dags/git_oncokb-airflow-dags/oncokb/msk_dags"
  # Enabling xcom pickling allows objects to be serialized. https://docs.python.org/3/library/pickle.html
  - name: AIRFLOW__CORE__ENABLE_XCOM_PICKLING
    value: "true"
  # The base url for airflow web. This is used so we get the correct log urls. https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#base-url
  - name: AIRFLOW__WEBSERVER__BASE_URL
    value: "http://airflow.oncokb.org"
  # Should be disabled in production. https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#load-default-connections
  - name: AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS
    value: "false"

# Installing extra python packages - https://github.com/bitnami/charts/tree/main/bitnami/airflow#install-extra-python-packages
web:
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/
  extraVolumes:
    - name: requirements
      configMap:
        name: oncokb-airflow-requirements

scheduler:
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/
  extraVolumes:
    - name: requirements
      configMap:
        name: oncokb-airflow-requirements
        
worker:
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/
  extraVolumes:
    - name: requirements
      configMap:
        name: oncokb-airflow-requirements
