apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/service-port: "6379"
  labels:
    app.kubernetes.io/instance: ingress
  name: cbioportal-ingress-dev
  namespace: default
spec:
  rules:
    - host: redis-dev.cbioportal.org
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cbioportal-public-persistence-redis-dev
              port:
                number: 6379
  tls:
    - hosts:
        - redis-dev.cbioportal.org
      secretName: redis-dev-cbioportal-cert
