controller:
  config:
    client-header-buffers: 16k
    large-client-header-buffers: 4 16k
    log-format-escape-json: "true"
    proxy-body-size: 1024m
    proxy-buffer-size: 16k
    proxy-buffers: 16k
    proxy-connect-timeout: "300"
    proxy-read-timeout: "300"
    proxy-send-timeout: "300"
    use-proxy-protocol: "true"
  image:
    tag: "v1.2.1"
  metrics:
    enabled: true
  replicaCount: 2
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  stats:
    enabled: true
