apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oncokb-ingress
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
      - www.oncokb.aws.mskcc.org
      - core.oncokb.aws.mskcc.org
      - curation.oncokb.aws.mskcc.org
      - cbx.oncokb.aws.mskcc.org
      - pub-data-17.oncokb.aws.mskcc.org
      - airflow.oncokb.aws.mskcc.org
  rules:
    - host: "www.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-public
                port:
                  number: 9095
    - host: "core.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-core
                port:
                  number: 8888
    - host: "cbx.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-core-cbx
                port:
                  number: 8888
    - host: "pub-data-17.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-core-pub-data-2017
                port:
                  number: 8888
    - host: "curation.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-curation
                port:
                  number: 8888
    - host: "airflow.oncokb.aws.mskcc.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: oncokb-airflow
                port:
                  number: 8080
  ingressClassName: nginx
